# Generated by Django 3.2.3 on 2021-06-23 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prod_Cat',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('user_phone', models.IntegerField(default=None)),
                ('prod_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('prod_cat', models.TextField(default=None, max_length=30)),
                ('prod_title', models.TextField(default=None, max_length=50)),
                ('prod_desc', models.CharField(default=None, max_length=200)),
                ('prod_condition', models.TextField(default=None, max_length=4)),
                ('prod_price', models.IntegerField(default=None)),
                ('prod_location', models.TextField()),
                ('prod_date', models.DateTimeField()),
                ('image1', models.ImageField(default=None, upload_to='media/images/')),
                ('image2', models.ImageField(default=True, upload_to='media/images/')),
                ('image3', models.ImageField(default=True, upload_to='media/images/')),
                ('image4', models.ImageField(default=True, upload_to='media/images/')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
