# Generated by Django 3.2.3 on 2021-06-29 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210623_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod_cat',
            name='cat_slug',
            field=models.TextField(default='', max_length=20),
        ),
    ]
