# Generated by Django 3.2.3 on 2021-07-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_prod_cat_cat_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='token',
            field=models.TextField(default='', max_length=100),
        ),
    ]
