# Generated by Django 3.2.3 on 2021-07-04 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='token',
        ),
    ]
