# Generated by Django 3.2 on 2021-07-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod_cat',
            name='cat_total',
            field=models.IntegerField(default=0),
        ),
    ]
