# Generated by Django 3.2 on 2021-07-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_prod_cat_cat_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod_cat',
            name='cat_total',
        ),
    ]
